### ISSUE TITLE
Consider not emitting empty test files

### ISSUE THREAD

**Issue by mfollett** [kratiahuja/broccoli-tslinter#1]
Right now when `disableTestGenerator` is true this plugin emits empty JS files. This clutters up the output directory. Why not just skip emitting a file altogether in that case?

**Comment by kratiahuja** [comment]
Hey @mfollett, sorry for the delayed response. I was on vacation and I am still catching up. I'll look into this and reply by soon.

**Comment by kratiahuja** [comment]
I think [PR](https://github.com/kratiahuja/broccoli-tslinter/pull/6) would probably fix this issue.

**Comment by kratiahuja** [comment]
Closing this. Please reopen if the PR hasn't fixed the issue.
