### ISSUE TITLE
Change `targetExtension` to `lint-test.js`?

### ISSUE THREAD

**Issue by rwjblue** [kratiahuja/broccoli-tslinter#13]
This would allow a few things:

* it would play nicely with the `nolint` option that ember-cli-qunit adds by default
* it would ensure that we do not need `*.ts` processing after linting (currently we return `.ts` files with only valid `.js` content, but that could change in the future and I wouldn't want to embed `**/*.ts` into concat's of only JS things)...

**Comment by rwjblue** [comment]
Here is a link to the example that made me think of this issue: https://github.com/tildeio/simple-html-tokenizer/pull/41/files#r97114924

**Comment by kratiahuja** [comment]
> it would ensure that we do not need *.ts processing after linting (currently we return .ts files with only valid .js content, but that could change in the future and I wouldn't want to embed **/*.ts into concat's of only JS things)...

I am not sure I follow the context here. Could you please elaborate?

**Comment by rwjblue** [comment]
Sorry, after re-reading I see that it doesn't make sense. 😝 

The point that I am making is that, the output of `broccoli-tslint` actually has to be transpiled today (since it emits `.ts` files), even though the file contents are valid `.js`.  This adds an additional unneeded step to a consuming build pipeline.

My concern is that folks would do what @turbo87 did in https://github.com/tildeio/simple-html-tokenizer/pull/41/files#r97114924 and just use `broccoli-concat` to concat `['**/*.js', '**/*.ts']` together into a `.js` output file, which might be catastrophic...

**Comment by kratiahuja** [comment]
Ohoo ok now I understand. Yes I agree it is an uneeded step for concat. I will update the `targetExtension` to output `lint-test.js`.
